# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('prize', models.PositiveIntegerField()),
                ('photo', models.ImageField(default='static/cat.jpeg', upload_to='ownerphotos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.CarAd')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='static/cat.jpeg', upload_to='ownerphotos')),
            ],
        ),
        migrations.AddField(
            model_name='carad',
            name='categories',
            field=models.ManyToManyField(related_name='carads', to='marketapp.Category'),
        ),
        migrations.AddField(
            model_name='carad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Owner'),
        ),
    ]
