# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(default='ownerphotos/default.png', upload_to='ownerphotos'),
        ),
    ]
