# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_auto_20171031_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='photo',
            field=models.ImageField(default='ownerphotos/default.png', upload_to='ownerphotos'),
        ),
    ]
