# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_auto_20171031_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='photo',
            field=models.ImageField(default='carphotos/default.jpg', upload_to='carphotos'),
        ),
    ]
